<!-- view/admin.phtml -->

<div class="page-header">
  <h1>Administration</h1>
</div>

<h2>Dragons</h2>

<p class="text-right"><button type="button" class="btn btn-primary btn-sm" onclick="$('#formDragonAdd').toggle();">+ NOUVEAU</button></p>

<div id="formDragonAdd" class="well col-md-6 col-md-offset-6" style="display: none">
  <form action="" method="post" role="form">
    <div class="form-group">
      <input name="dragonName" type="text" placeholder="Nom" class="form-control">
    </div>
    <div class="form-group">
      <input name="dragonLifeMax" type="text" placeholder="Vie max." class="form-control">
    </div>
    <div class="form-group">
      <input name="dragonForce" type="text" placeholder="Force" class="form-control">
    </div>
    <input name="action" value="dragonAdd" type="hidden">
    <input value="AJOUTER" type="submit" class="btn btn-default">
  </form>
</div>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th class="col-md-1">Id</th>
      <th class="col-md-6">Nom</th>
      <th class="col-md-2">Vie max.</th>
      <th class="col-md-2">Force</th>
      <th class="col-md-1"></th>
    </tr>
  </thead>
  <tbody>
    <?php foreach($dragons as $dragon): ?>
      <tr>
        <td><?= $dragon['dragonId'] ?></td>
        <td><?= $dragon['dragonName'] ?></td>
        <td><?= $dragon['dragonLifeMax'] ?></td>
        <td><?= $dragon['dragonForce'] ?></td>
        <td><a href="index.php?menu=admin&dragonId=<?= $dragon['dragonId'] ?>&action=dragonDelete" type="button" class="btn btn-danger btn-xs">SUPPRIMER</a></td>
      </tr>
    <?php endforeach ?>
  </tbody>
</table>

<h2>Personnages</h2>

<p class="text-right"><button type="button" class="btn btn-primary btn-sm" onclick="$('#formCharacterAdd').toggle();">+ NOUVEAU</button></p>

<div id="formCharacterAdd" class="well col-md-6 col-md-offset-6" style="display: none">
  <form action="" method="post" role="form">
    <div class="form-group">
      <input name="characterName" type="text" placeholder="Nom" class="form-control">
    </div>
    <div class="form-group">
      <input name="characterLifeMax" type="text" placeholder="Vie max." class="form-control">
    </div>
    <div class="form-group">
      <input name="characterArmor" type="text" placeholder="Armure" class="form-control">
    </div>
    <input name="action" value="characterAdd" type="hidden">
    <input value="AJOUTER" type="submit" class="btn btn-default">
  </form>
</div>

<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th class="col-md-1">Id</th>
      <th class="col-md-6">Nom</th>
      <th class="col-md-2">Vie max.</th>
      <th class="col-md-2">Armure</th>
      <th class="col-md-1"></th>
    </tr>
  </thead>
  <tbody>
    <?php foreach($characters as $character): ?>
      <tr>
        <td><?= $character['characterId'] ?></td>
        <td><?= $character['characterName'] ?></td>
        <td><?= $character['characterLifeMax'] ?></td>
        <td><?= $character['characterArmor'] ?></td>
        <td><a href="index.php?menu=admin&characterId=<?= $character['characterId'] ?>&action=characterDelete" type="button" class="btn btn-danger btn-xs">SUPPRIMER</a></td>
      </tr>
    <?php endforeach ?>
  </tbody>
</table>

<h2>Armes</h2>

<p class="text-right"><button type="button" class="btn btn-primary btn-sm" onclick="$('#formWeaponAdd').toggle();">+ NOUVEAU</button></p>

<div id="formWeaponAdd" class="well col-md-6 col-md-offset-6" style="display: none">
  <form action="" method="post" role="form">
    <div class="form-group">
      <input name="weaponName" type="text" placeholder="Nom" class="form-control">
    </div>
    <div class="form-group">
      <input name="weaponForce" type="text" placeholder="Force" class="form-control">
    </div>
    <input name="action" value="weaponAdd" type="hidden">
    <input value="AJOUTER" type="submit" class="btn btn-default">
  </form>
</div>

<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th class="col-md-1">Id</th>
      <th class="col-md-8">Nom</th>
      <th class="col-md-2">Force</th>
      <th class="col-md-1"></th>
    </tr>
  </thead>
  <tbody>
    <?php foreach($weapons as $weapon): ?>
      <tr>
        <td><?= $weapon['weaponId'] ?></td>
        <td><?= $weapon['weaponName'] ?></td>
        <td><?= $weapon['weaponForce'] ?></td>
        <td><a href="index.php?menu=admin&weaponId=<?= $weapon['weaponId'] ?>&action=weaponDelete" type="button" class="btn btn-danger btn-xs">SUPPRIMER</a></td>
      </tr>
    <?php endforeach ?>
  </tbody>
</table>

<h2>Utilisateurs</h2>

<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th class="col-md-1">Id</th>
      <th class="col-md-8">Nom</th>
      <th class="col-md-2">E-mail</th>
      <th class="col-md-1"></th>
    </tr>
  </thead>
  <tbody>
    <?php foreach($users as $user): ?>
      <tr>
        <td><?= $user['userId'] ?></td>
        <td><?= $user['userName'] ?></td>
        <td><?= $user['userEmail'] ?></td>
        <td><a href="index.php?menu=admin&userId=<?= $user['userId'] ?>&action=userDelete" type="button" class="btn btn-danger btn-xs">SUPPRIMER</a></td>
      </tr>
    <?php endforeach ?>
  </tbody>
</table>
