<!-- view/home.phtml -->

<div class="page-header">
  <h2 id="container">Categories</h2>
  <div class="list-group">
    <?php foreach ($categories as $categorie): ?>
      <a href="index.php?action=categorieSelect&idCategorie=<?= $categorie['idCategorie'] ?>" class="list-group-item<?php if($categorie['idCategorie'] == $_SESSION['selectedIdCategorie']): ?> active<?php endif ?>"><?= $categorie['nomCategorie'] ?></a>
    <?php endforeach ?>
  </div>
</div>

<?php if($_SESSION['selectedIdCategorie'] == 1): ?>

<div class="col-md-4">
  <h3> Ordinateur </h3>
  <div class="list-group">
    <?php foreach ($produits as $produit): ?>
      <a href="index.php?action=produitSelect&idProduit=<?= $produit['idProduit'] ?>" class="list-group-item<?php if($produit['idProduit'] == $_SESSION['selectedIdProduit']): ?> active<?php endif ?>"><?= $produit['nomProduit'] ?></a>
    <?php endforeach ?>
  </div>
</div>

<!-- si le client clique sur un produit -> afficher les details de ce produit choisit en cours-->
<?php if($produit['idProduit'] == $_SESSION['selectedIdProduit']): ?>

<!--afficher les details de ce produit choisit en cours-->
<table class="table table-striped table-hover">
    <thead>
      <tr>
        <th class="col-md-2"><h5> Détails de <?php endif ?><?= $produit['nomProduit']  ?></h5></th>      
      </tr>
      <tr>         
        <th class="col-md-1">Reference</th>
        <th class="col-md-6">Nom de produit</th>
        <th class="col-md-2">Desription</th>    
        <th class="col-md-1"></th>
      </tr>
    </thead>
    <tbody>
      <?php foreach($details as $detail): ?>
        <tr>            
            <td><?= $detail['refProduit'] ?></td>
            <td><?= $detail['nomProduit'] ?></td>
            <td><?= $detail['descriptionProduit'] ?></td>
            <td><a href="index.php?menu=admin&idProduit=<?= $detail['idProduit'] ?>&action=produitDelete" type="button" class="btn btn-danger btn-xs">SUPPRIMER</a></td>
        </tr>
      <?php endforeach ?>
    </tbody>
</table>



<?php elseif($_SESSION['selectedIdCategorie'] == 2):?>
<div class="col-md-4">
  <h3>TV</h3>
    <div class="list-group">
    <?php foreach ($produits as $produit): ?>
      <a href="index.php?action=produitSelect&idProduit=<?= $produit['idProduit'] ?>" class="list-group-item<?php if($produit['idProduit'] == $_SESSION['selectedIdProduit']): ?> active<?php endif ?>"><?= $produit['nomProduit'] ?></a>
    <?php endforeach ?>
  </div>
</div>
<?php //endif ?>

<!-- si le client clique sur un produit -> afficher les details de ce produit choisit en cours-->
<?php if($produit['idProduit'] == $_SESSION['selectedIdProduit']): ?>

<!--afficher les details de ce produit choisit en cours-->
<table class="table table-striped table-hover">
    <thead>
      <tr>
        <th class="col-md-2"><h5> Détails de <?php endif ?><?= $produit['nomProduit']  ?></h5></th>      
      </tr>
      <tr>         
        <th class="col-md-1">Reference</th>
        <th class="col-md-6">Nom de produit</th>
        <th class="col-md-2">Desription</th>    
        <th class="col-md-1"></th>
      </tr>
    </thead>
    <tbody>
      <?php foreach($details as $detail): ?>
        <tr>            
            <td><?= $detail['refProduit'] ?></td>
            <td><?= $detail['nomProduit'] ?></td>
            <td><?= $detail['descriptionProduit'] ?></td>
            <td><a href="index.php?menu=admin&idProduit=<?= $detail['idProduit'] ?>&action=produitDelete" type="button" class="btn btn-danger btn-xs">SUPPRIMER</a></td>
        </tr>
      <?php endforeach ?>
    </tbody>
</table>


<?php elseif($_SESSION['selectedIdCategorie'] == 3): ?>
<div class="col-md-4">
  <h3>Telephone</h3>
     <div class="list-group">
    <?php foreach ($produits as $produit): ?>
      <a href="index.php?action=produitSelect&idProduit=<?= $produit['idProduit'] ?>" class="list-group-item<?php if($produit['idProduit'] == $_SESSION['selectedIdProduit']): ?> active<?php endif ?>"><?= $produit['nomProduit'] ?></a>      
    <?php endforeach ?>
  </div>
</div>


<!-- si le client clique sur un produit -> afficher les details de ce produit choisit en cours-->
<?php if($produit['idProduit'] == $_SESSION['selectedIdProduit']): ?>

<!--afficher les details de ce produit choisit en cours-->
<table class="table table-striped table-hover">
    <thead>
      <tr>
        <th class="col-md-2"><h5> Détails de <?php endif ?><?= $produit['nomProduit']  ?></h5></th>      
      </tr>
      <tr>         
        <th class="col-md-1">Reference</th>
        <th class="col-md-6">Nom de produit</th>
        <th class="col-md-2">Desription</th>    
        <th class="col-md-1"></th>
      </tr>
    </thead>
    <tbody>
      <?php foreach($details as $detail): ?>
        <tr>            
            <td><?= $detail['refProduit'] ?></td>
            <td><?= $detail['nomProduit'] ?></td>
            <td><?= $detail['descriptionProduit'] ?></td>
            <td><a href="index.php?menu=admin&idProduit=<?= $detail['idProduit'] ?>&action=produitDelete" type="button" class="btn btn-danger btn-xs">SUPPRIMER</a></td>
        </tr>
      <?php endforeach ?>
    </tbody>
</table>

<?php endif ?>