<!-- view/home.phtml -->

<div class="page-header">
  <h2 id="container">Categories</h2>
  <div class="list-group">
    <?php foreach ($categories as $categorie): ?>
      <a href="index.php?action=categorieSelect&idCategorie=<?= $categorie['idCategorie'] ?>" class="list-group-item<?php if($categorie['idCategorie'] == $_SESSION['selectedIdCategorie']): ?> active<?php endif ?>"><?= $categorie['nomCategorie'] ?></a>
    <?php endforeach ?>
  </div>
</div>

<?php if($produitIsReady = true) : ?>
  <div class="page-header">
    <h3 id="container"><?= $categorie['nomCategorie'] ?></h3>
   
    <div class="list-group">
      <?php foreach ($produits as $produit): ?>
        <a href="index.php?action=produitSelect&idProduit=<?= $produit['idProduit'] ?>" class="list-group-item<?php if($produit['idProduit'] == $_SESSION['selectedIdProduit']): ?> active<?php endif ?>"><?= $produit['nomProduit'] ?></a>
      <?php endforeach ?>      
    </div>
  </div>
<?php endif ?>

  <!-- si le client clique sur un produit -> afficher les details de ce produit choisit en cours-->
  <?php if($produit['idProduit'] == $_SESSION['selectedIdProduit']) : ?>
    <div class="page-header">
    <?php foreach($details as $detail): ?>
    <h3 id="container"><h5> Détails de <?= $detail['nomProduit']  ?></h5>  
    <!--afficher les details de ce produit choisit en cours-->
    <table class="table table-striped table-hover">        
        <thead>         
          <tr>         
            <th class="col-md-1">Reference</th>
            <th class="col-md-2">Nom de produit</th>
            <th class="col-md-2">Prix TTC</th>
            <th class="col-md-8">Desription</th>    
            <th class="col-md-1"></th>
          </tr>
        </thead>
        <tbody>          
          <tr>            
              <td><?= $detail['refProduit'] ?></td>
              <td><?= $detail['nomProduit'] ?></td>
              <td><?=  50 . "€" ?></td>
              <td><?= $detail['descriptionProduit'] ?></td>
              <td><a href="index.php?menu=admin&idProduit=<?= $detail['idProduit'] ?>&action=produitDelete" type="button" class="btn btn-danger btn-xs">SUPPRIMER</a></td>
          </tr>  
        </tbody>    
    </table>  
  <?php //endforeach ?>     
<?php endif ?>
