<?php if ($gameIsReady): ?>

    <div class="col-md-4 text-center">
        <img src="img/character.png" alt="" style="height: 420px; margin-bottom: 20px">
        <div class="progress progress-striped active">
            <div class="progress-bar" style="width: 50%"></div>
        </div>
        <p><a href="index.php?action=characterAttack" class="btn btn-warning">ATTAQUER LE DRAGON</a></p>
        <ul class="list-group text-left" style="margin-top: 20px">
            <li class="list-group-item">
                <span class="badge">NomDuPersonnage</span>
                Nom
            </li>
            <li class="list-group-item">
                <span class="badge">0</span>
                Vie max.
            </li>
            <li class="list-group-item">
                <span class="badge">0</span>
                Armure
            </li>
            <li class="list-group-item">
                <span class="badge">NomDeLArme</span>
                Arme
            </li>
            <li class="list-group-item">
                <span class="badge">0</span>
                Force
            </li>
        </ul>
    </div>

    <div class="col-md-4 col-md-offset-4 text-center">
        <img src="img/dragon.png" alt="" style="height: 420px; margin-bottom: 20px">
        <div class="progress progress-striped active">
            <div class="progress-bar" style="width: 50%"></div>
        </div>
        <p><a href="index.php?action=dragonAttack" class="btn btn-warning">ATTAQUER LE PERSONNAGE</a></p>
        <ul class="list-group text-left" style="margin-top: 20px">
            <li class="list-group-item">
                <span class="badge">NomDuDragon</span>
                Nom
            </li>
            <li class="list-group-item">
                <span class="badge">0</span>
                Vie max.
            </li>
            <li class="list-group-item">
                <span class="badge">0</span>
                Force
            </li>
        </ul>
    </div>

<?php endif ?>

<div class="clearfix"></div>

<div class="page-header">
    <h2 id="container">Sélection</h2>
</div>

<div class="col-md-4">
    <h3>Dragons</h3>
    <div class="list-group">
        <?php foreach ($dragonsArray as $dragonArray): ?>
            <a href="index.php?action=dragonSelect&dragonId=<?= $dragonArray['dragonId'] ?>" class="list-group-item"><?= $dragonArray['dragonName'] ?></a>
        <?php endforeach ?>
    </div>
</div>

<div class="col-md-4">
    <h3>Personnages</h3>
    <div class="list-group">
        <?php foreach ($charactersArray as $characterArray): ?>
            <a href="index.php?action=characterSelect&characterId=<?= $characterArray['characterId'] ?>" class="list-group-item"><?= $characterArray['characterName'] ?></a>
        <?php endforeach ?>
    </div>
</div>

<div class="col-md-4">
    <h3>Armes</h3>
    <div class="list-group">
        <?php foreach ($weaponsArray as $weaponArray): ?>
            <a href="index.php?action=weaponSelect&weaponId=<?= $weaponArray['weaponId'] ?>" class="list-group-item"><?= $weaponArray['weaponName'] ?></a>
        <?php endforeach ?>
    </div>
</div>
