<!-- view/signup.phtml -->

<div class="page-header">
  <h2 id="container">Inscription</h2>
</div>

<form name="userSignUp" method="post" action="" class="form-horizontal">
  <fieldset>
    <div class="form-group">
      <label class="col-lg-2 control-label">Nom</label>
      <div class="col-lg-10">
        <input type="text" class="form-control" name="userName" placeholder="Nom" autocomplete="off">
      </div>
    </div>
    <div class="form-group">
      <label class="col-lg-2 control-label">E-mail</label>
      <div class="col-lg-10">
        <input type="email" class="form-control" name="userEmail" placeholder="E-mail" autocomplete="off">
      </div>
    </div>
    <div class="form-group">
      <label class="col-lg-2 control-label">Mot de passe</label>
      <div class="col-lg-10">
        <input type="password" class="form-control" name="userPassword" placeholder="Mot de passe" autocomplete="off">
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <button type="submit" class="btn btn-primary">S'INSCRIRE</button>
      </div>
    </div>
  </fieldset>
  <input name="action" value="userSignUp" type="hidden">
</form>
