<!-- view/top.phtml -->

<!doctype html>
<html>
  
  <head>
      <meta charset="utf-8">

      <title>Dragons Slayer (is back)</title>
      
      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

      <!-- Bootstrap theme : Bootswatch Superhero -->
      <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootswatch/3.2.0/superhero/bootstrap.min.css">
      
      <!-- JQuery -->
      <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>

      <!-- Bootstrap JS -->
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  </head>

  <body>

    <nav class="navbar navbar-default" role="navigation">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="index.php">Dragons Slayer</a>
      </div>
      <div class="navbar-collapse collapse navbar-responsive-collapse">

        <?php if ($userIsConnected): ?>
          <ul class="nav navbar-nav navbar-left">
            <li><a href="index.php?menu=admin">Administration</a></li>
            <li><a href="index.php?action=userDisconnect">Déconnexion</a></li>
          </ul>
        <?php else: ?>
          <ul class="nav navbar-nav navbar-left">
            <li><a href="index.php?menu=signup">Inscription</a></li>
          </ul>
          <form method="post" action="" class="navbar-form navbar-right">
            <div class="form-group">
              <input name="userEmail" type="text" class="form-control col-lg-4" placeholder="E-mail" autocomplete="off">
            </div>
            <div class="form-group">
              <input name="userPassword" type="password" class="form-control col-lg-4" placeholder="Mot de passe" autocomplete="off">
            </div>
            <div class="checkbox">
              <input name="userDoNotForget" value="1" type="checkbox"> Se souvenir de moi
            </div>
            <input name="action" value="userConnect" type="hidden">
            <button type="submit" class="btn btn-default">CONNEXION</button>
          </form>
        <?php endif ?>

      </div>
    </nav>

    <div class="container">
