<div class="page-header">
  <h1>Administration</h1>
</div>

<h2>Commandes</h2>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th class="col-md-1">Id</th>
      <th class="col-md-2">Date</th>
      <th class="col-md-1">Total</th>
      <th class="col-md-8">Client</th>
      <th class="col-md-1"></th>
    </tr>
  </thead>
  <tbody>
    <?php foreach($ordersList as $order): ?>
      <tr>
        <td><?= $order['orderId'] ?></td>
        <td><?= $order['orderDate'] ?></td>
        <td><?= number_format($order['orderTotalPrice'], 2) ?> €</td>
        <td>
          <?= $order['customerCivility'] . '  ' . $order['customerLastName'] . '  ' . $order['customerFirstName'] ?><br>
          <?= $order['customerAddress'] ?><br>
          <?= $order['customerZipCode'] . ' ' . $order['customerCity'] ?>
        </td>
        <td><a href="index.php?menu=administration&amp;orderId=<?= $order['orderId'] ?>&amp;action=orderDelete" type="button" class="btn btn-danger btn-xs">SUPPRIMER</a></td>
      </tr>
    <?php endforeach ?>
  </tbody>
</table>

<h2>Clients</h2>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th class="col-md-1">Id</th>
      <th class="col-md-3">Nom</th>
      <th class="col-md-4">Adresse</th>
      <th class="col-md-1">CP</th>
      <th class="col-md-2">Ville</th>
      <th class="col-md-1"></th>
    </tr>
  </thead>
  <tbody>
    <?php foreach($customersList as $customer): ?>
      <tr>
        <td><?= $customer['customerId'] ?></td>
        <td><?= $customer['customerCivility'] . '  ' . $customer['customerLastName'] . '  ' . $customer['customerFirstName'] ?></td>
        <td><?= $customer['customerAddress'] ?></td>
        <td><?= $customer['customerZipCode'] ?></td>
        <td><?= $customer['customerCity'] ?></td>
        <td><a href="index.php?menu=administration&amp;customerId=<?= $customer['customerId'] ?>&amp;action=customerDelete" type="button" class="btn btn-danger btn-xs">SUPPRIMER</a></td>
      </tr>
    <?php endforeach ?>
  </tbody>
</table>

<h2>Produits</h2>

<p class="text-right">
  <button id="productAddButton" type="button" class="btn btn-primary btn-sm">+ Nouveau produit</button>
</p>

<div id="formProductAdd" class="well col-md-6 col-md-offset-6 hidden">

  <form action="" enctype="multipart/form-data" method="post" role="form">

    <div class="form-group">
      <input name="productName" type="text" placeholder="Nom" class="form-control">
    </div>
    <div class="form-group">
      <select name="categoryId" class="form-control">
        <?php foreach($categoriesList as $category): ?>
          <option value="<?= $category['categoryId'] ?>"><?= $category['categoryName'] ?></option>
        <?php endforeach ?>
      </select>
    </div>
    <div class="form-group">
      <textarea name="productDescription" class="form-control" rows="2" placeholder="Description"></textarea>
    </div>
    <div class="form-group input-group">
      <input name="productPrice" value="0.00" type="text" placeholder="Prix" class="form-control">
      <span class="input-group-addon">€</span>
    </div>
    <div class="form-group">
      <input name="productImage" type="file" accept="image/*" class="form-control">
    </div>
    <input name="action" value="productAdd" type="hidden">
    <input value="AJOUTER" type="submit" class="btn btn-default">
  </form>
</div>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th class="col-md-1">Id</th>
      <th class="col-md-2">Nom</th>
      <th class="col-md-5">Description</th>
      <th class="col-md-2">Catégorie</th>
      <th class="col-md-1">Prix</th>
      <th class="col-md-1"></th>
    </tr>
  </thead>
  <tbody>
    <?php foreach($productsList as $product): ?>
      <tr>
        <td><?= $product['productId'] ?></td>
        <td><?= $product['productName'] ?></td>
        <td><?= $product['productDescription'] ?></td>
        <td><?= $product['categoryName'] ?></td>
        <td><?= number_format($product['productPrice'], 2) ?> €</td>
        <td><a href="index.php?menu=administration&amp;productId=<?= $product['productId'] ?>&amp;action=productDelete" type="button" class="btn btn-danger btn-xs">SUPPRIMER</a></td>
      </tr>
    <?php endforeach ?>
  </tbody>
</table>

<h2>Catégories</h2>

<p class="text-right">
  <button id="categoryAddButton" type="button" class="btn btn-primary btn-sm">+ Nouvelle catégorie</button>
</p>

<div id="formCategoryAdd" class="well col-md-6 col-md-offset-6 hidden">
  <form action="" method="post" role="form">
    <div class="form-group">
      <input name="categoryName" type="text" placeholder="Nom" class="form-control">
    </div>
    <input name="action" value="categoryAdd" type="hidden">
    <input value="AJOUTER" type="submit" class="btn btn-default">
  </form>
</div>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th class="col-md-1">Id</th>
      <th class="col-md-10">Nom</th>
      <th class="col-md-1"></th>
    </tr>
  </thead>
  <tbody>
    <?php foreach($categoriesList as $category): ?>
      <tr>
        <td><?= $category['categoryId'] ?></td>
        <td><?= $category['categoryName'] ?></td>
        <td><a href="index.php?menu=administration&amp;categoryId=<?= $category['categoryId'] ?>&amp;action=categoryDelete" type="button" class="btn btn-danger btn-xs">Supprimer</a></td>
      </tr>
    <?php endforeach ?>
  </tbody>
</table>
