
  </div>
  <!-- /.container -->

  <div class="container">

    <hr>

    <!-- Footer -->
    <footer>
      <div class="row">
        <div class="col-lg-12">
            
          <?php if ($customerIsConnected): ?>
            <p class="pull-right">
              Vous êtes connecté en tant que :
              <b><?= $_SESSION['customerArray']['customerFirstName'] . '  ' . $_SESSION['customerArray']['customerLastName'] ?>.</b>
            </p>
          <?php endif ?>
          
          <p>Copyright &copy; Allo Rapido Pizza <?= date("Y") ?>.</p>

        </div>
      </div>
    </footer>

  </div>
  <!-- /.container -->

  <!-- jQuery -->
  <script src="//code.jquery.com/jquery-2.1.1.min.js"></script>

  <!-- Bootstrap : JavaScript -->
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>

  <!-- Javascript personnalisé -->
  <script src="view/js/main.js"></script>

</body>

</html>
