<!-- view/shop.phtml -->

<div class="page-header">
    <h1>Nos produits</h1>
</div>

<ol class="breadcrumb">
    <li><a href="index.php">Nos produits</a></li>
    <?php if ($selectedCategoryName): ?>
        <li><a href="#"><?= $selectedCategoryName ?></a></li>
    <?php endif ?>
</ol>

<div class="row">

    <div class="col-md-8">

        <div class="row">

            <?php if (!$selectedCategoryName): ?>

                <?php foreach($categoriesList as $category): ?>

                    <div class="col-sm-4 col-lg-4 col-md-4">
                        <div class="thumbnail">
                            <img src="http://placehold.it/320x150" alt="">
                            <div class="caption">
                                <h3><?= $category['categoryName'] ?></h3>
                            </div>
                            <div class="text-right product-button">
                                <a href="index.php?categoryId=<?= $category['categoryId'] ?>" class="btn btn-info">Choisir cette catégorie</a>
                            </div>
                        </div>
                    </div>

                <?php endforeach ?>

            <?php else: ?>

                <?php foreach($productsList as $product): ?>

                    <div class="col-sm-4 col-lg-4 col-md-4">
                        <div class="thumbnail">
                            <?php if(file_exists('view/img/products/' . $product['productId'] . '.jpg')): ?>
                                <div class="product-image" style="background-image: url('view/img/products/<?= $product['productId'] ?>.jpg');"></div>
                            <?php else: ?>
                                <div class="product-image"></div>
                            <?php endif ?>
                            <div class="caption">
                                <h4 class="pull-right"><?= $product['productPrice'] ?> €</h4>
                                <h4><?= $product['productName'] ?></h4>
                                <p><?= $product['productDescription'] ?></p>
                            </div>
                            <div class="text-right product-button">
                                <a href="index.php?<?php if ($selectedCategoryName) echo 'categoryId=' . $_GET['categoryId'] . '&amp;'; ?>productId=<?= $product['productId'] ?>&amp;action=cartProductAdd" class="btn btn-primary">Ajouter au panier</a>
                            </div>
                        </div>
                    </div>

                <?php endforeach ?>

            <?php endif ?>

        </div>

    </div>

    <div id="cart" class="col-md-4">
        <div class="panel  panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Panier</h3>
            </div>
            <div class="panel-body">

                <?php if ($cartIsEmpty): ?>

                    <p>La faim justifie les moyens !</p>

                <?php else: ?>

                    <ul class="list-group">

                        <?php foreach($cartProductsList as $cartProduct): ?>
                            <li class="list-group-item">
                                <p>
                                    <a href="index.php?<?php if ($selectedCategoryName) echo 'categoryId=' . $_GET['categoryId'] . '&amp;'; ?>n=<?= $cartProduct['n'] ?>&amp;action=cartProductRemove">
                                        <i class="glyphicon glyphicon-remove"></i>
                                    </a>
                                    <b><?= $cartProduct['productName'] ?></b>
                  <span class="pull-right">
                    <?= number_format($cartProduct['productPrice'] * $cartProduct['cartProductQuantity'], 2) ?> €
                  </span>
                                </p>
                                <p>
                                    Quantité :
                                    <a href="index.php?<?php if ($selectedCategoryName) echo 'categoryId=' . $_GET['categoryId'] . '&amp;'; ?>n=<?= $cartProduct['n'] ?>&amp;action=cartProductQuantityDecrease">
                                        <i class="glyphicon glyphicon-minus"></i>
                                    </a>
                                    <b><?= $cartProduct['cartProductQuantity'] ?></b>
                                    <a href="index.php?<?php if ($selectedCategoryName) echo 'categoryId=' . $_GET['categoryId'] . '&amp;'; ?>n=<?= $cartProduct['n'] ?>&amp;action=cartProductQuantityIncrease">
                                        <i class="glyphicon glyphicon-plus"></i>
                                    </a>
                                </p>
                            </li>
                        <?php endforeach ?>

                        <li class="list-group-item">
                            <p>
                                <b>TOTAL</b>
                <span class="pull-right">
                  <b><?= $cartTotalPrice ?> €</b>
                </span>
                            </p>
                        </li>

                    </ul>

                    <p class="text-right"><a href="index.php?<?php if (!$customerIsConnected) echo 'menu=signup&amp;'; ?>action=orderSend" class="btn btn-success">COMMANDER</a></p>

                <?php endif ?>

            </div>
        </div>
    </div>

</div>
