<!DOCTYPE html>
<html lang="fr">

<head>
  
  <meta charset="utf-8">

  <title>Allo Rapido Pizza</title>

  <!-- Bootstrap : CSS -->
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet">

  <!-- CSS personnalisé -->
  <link href="view/css/main.css" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    
    <div class="container">
      
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="index.php">Allo Rapido Pizza</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Nos produits <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <?php foreach($categoriesList as $category): ?>
                <li><a href="index.php?categoryId=<?= $category['categoryId'] ?>"><?= $category['categoryName'] ?></a></li>
              <?php endforeach ?>
            </ul>
          </li>
          
          <?php if (!$customerIsConnected): ?>
            <li><a href="index.php?menu=signup">Inscription</a></li>
          <?php endif ?>
          
          <li><a href="index.php?menu=administration">Administration</a></li>

        </ul>

        <?php if ($customerIsConnected): ?>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="index.php?action=customerDisconnect">Déconnexion</a></li>
          </ul>
        <?php else: ?>
          <form name="formCustomerConnect" action="" method="post" class="navbar-form navbar-right" role="search">
            <div class="form-group">
              <input name="customerEmail" type="email" class="form-control" placeholder="E-mail">
            </div>
            <div class="form-group">
              <input name="customerPassword" type="password" class="form-control" placeholder="Mot de passe">
            </div>
            <input name="action" value="customerConnect" type="hidden">
            <button type="submit" class="btn btn-default">Connexion</button>
          </form>
        <?php endif ?>

      </div>
      <!-- /.navbar-collapse -->

    </div>
    <!-- /.container -->

  </nav>


  <!-- Page Content -->
  <div class="container">
