<div class="page-header">
    <h1>INSCRIPTION</h1>
</div>

<h2>Membres</h2>

<p class="text-right"><button type="button" class="btn btn-primary btn-sm" onclick="$('#formUserAdd').toggle();">+ NOUVEAU</button></p>

<div id="formUserAdd" class="well col-md-6 col-md-offset-6" style="display: none">

    <form action ="" method= "post" role="form">
        <div class="form-group">
            <input type="text" name="username" placeholder="Username" class="form-control">
        </div>
        <div class="form-group">
            <input type="text" name="mdp" placeholder="Mot de passe" class="form-control">
        </div>
        <div class="form-group">
            <input type="text" name="nom" placeholder="Nom" class="form-control">
        </div>
        <div class="form-group">
            <input type="text" name="prenom" placeholder="Prénom." class="form-control">
        </div>
        <div class="form-group">
            <input type="text" name="email" placeholder="email" class="form-control">
        </div>

        <input value="S'inscrire" type="submit" class="btn btn-default">
        <input name="action" value="addUser" type = "hidden" >
    </form>
    
</div>


<table class="table table-striped table-hover">
    <thead>
    <tr>
    <th class="col-md-1">Id</th>
    <th class="col-md-1">Username</th>
    <th class="col-md-1">Mdp</th>
    <th class="col-md-1">Nom</th>
    <th class="col-md-1">Prenom</th>
    <th class="col-md-6">Email</th>
    <th class="col-md-1"></th>
    </thead>
    <tbody>
    <?php foreach($usersArray as $userArray): ?>
        <tr>
            <td><?= $userArray['userId'] ?></td>
            <td><?= $userArray['username'] ?></td>
            <td><?= $userArray['mdp'] ?></td>
            <td><?= $userArray['nom'] ?></td>
            <td><?= $userArray['prenom'] ?></td>
            <td><?= $userArray['email'] ?></td>
            <td><a href="index.php?menu=signup&userId=<?= $userArray['userId'] ?>&action=userDelete" type="button" class="btn btn-danger btn-xs">SUPPRIMER</a></td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>



