<!-- top2.phtml -->

<!doctype html>
<html>

<head>
    <meta charset="utf-8">

    <title>Dragons Slayer (is back)</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

    <!-- Bootstrap theme : Bootswatch Superhero -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootswatch/3.2.0/superhero/bootstrap.min.css">

    <!-- JQuery -->
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>

    <!-- Bootstrap JS -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</head>

<body>

<nav class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="index.php">Dragons Slayer</a>
    </div>
    <div class="navbar-collapse collapse navbar-responsive-collapse">

        <?php // Si l'utilisateur est connecté, on affiche l'accès à l'espace d'administration et le lien de déconnexion
                if(isset($connectedUserObj)) header('Location : admin.phtml') ; ?>
        <ul class="nav navbar-nav navbar-left">
            <li><a href="index.php?menu=admin">Administration</a></li>
            <!--li><a href="index.php?action=userDisconnect?userId=<?php $_SESSION['userId'] ?>"> Déconnexion</a></li-->
        </ul>
        <?php // Sinon on affiche le formulaire pour se connecter et le lien vers l'inscription ?>
        <ul class="nav navbar-nav navbar-left">
            <li><a href="index.php?menu=signup">Inscription</a></li>
        </ul>
        <form class="navbar-form navbar-right">
            <input name="username" type="text" class="form-control col-lg-4" placeholder="E-mail" autocomplete="off">
            <input name="mdp" type="password" class="form-control col-lg-4" placeholder="Mot de passe" autocomplete="off">
            <!-- ... -->
            <input type="submit" class="form-control col-lg-4" placeholder="Mot de passe" autocomplete="off">
        </form>
        <?php // Fin du si 
                endif ?>

    </div>
</nav>

<div class="container">
